name: flutter_google_map
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  map_view: "^0.0.12"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true



